"""Add meal plan entry model

Revision ID: 868c78eadf6e
Revises: 99070f67f86d
Create Date: 2026-01-16 13:50:00.618594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868c78eadf6e'
down_revision: Union[str, Sequence[str], None] = '99070f67f86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_entries_date'), 'meal_plan_entries', ['date'], unique=False)
    op.create_index(op.f('ix_meal_plan_entries_id'), 'meal_plan_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plan_entries_id'), table_name='meal_plan_entries')
    op.drop_index(op.f('ix_meal_plan_entries_date'), table_name='meal_plan_entries')
    op.drop_table('meal_plan_entries')
    # ### end Alembic commands ###
